apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-ui
  labels:
    {{- include "kozo-website.labels" . | nindent 4 }}
spec:
  {{- if not .Values.ui.autoscaling.enabled }}
  replicas: {{ .Values.ui.minReplicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kozo-website.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kozo-website.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kozo-website.serviceAccountName" . }}
      containers:
        - name: nextjs
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ui.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http

---
apiVersion: v1
kind: Service
metadata:
  name: website-ui
  labels:
    {{- include "kozo-website.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ui.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kozo-website.selectorLabels" . | nindent 4 }}
